// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHkDq8UCQc8Ngmf-EKBxve-DufjaUWe5U',
    appId: '1:469656845570:android:eb042a91f4a92fc2d9961b',
    messagingSenderId: '469656845570',
    projectId: 'hued-6877d',
    storageBucket: 'hued-6877d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA90kK2AonH4dzRumie0emwS0pl1Xs6Hws',
    appId: '1:469656845570:ios:50363cab49777539d9961b',
    messagingSenderId: '469656845570',
    projectId: 'hued-6877d',
    storageBucket: 'hued-6877d.firebasestorage.app',
    iosBundleId: 'com.live.hued',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8TKvwV7Ism38OrEyileVhsgxHz7n6QeY',
    appId: '1:469656845570:web:d0834de2898cb245d9961b',
    messagingSenderId: '469656845570',
    projectId: 'hued-6877d',
    authDomain: 'hued-6877d.firebaseapp.com',
    storageBucket: 'hued-6877d.firebasestorage.app',
    measurementId: 'G-C2ZWMCTH3Y',
  );

}